__version__ = "1.0.1"
__author__ = "Tht authors"
__author_email__ = "@"
__license__ = "?"
__url__ = r"https://github.com/CoronaHakab/CoronaHakabModel"
__slack__ = r"https://join.slack.com/t/covid19simulation/shared_invite/zt-cxm8qh8m-wqfADdf6vz3wLDFs0u9xVQ"
